balances:
  pooled_rune: thor1g98cy3n9mmjrpn0sxmn63lztelera37n8n67c0
  standby_reserve: thor1lj62pg6ryxv2htekqx04nv7wd3g98qf9gfvamy
  treasury_2: thor14n2q7tpemxcha8zc26j0g5pksx4x3a9xw9ryq9
  treasury_lp2: thor1wfe7hsuvup27lx04p5al4zlcnx6elsnyft7dzm
  treasury_multisig: thor1qd4my7934h2sn5ag5eaqsde39va4ex2asz3yv5
